Best JS Practices: Add To-Do List files to testing-branch
rmiyoyo/To-Do-List-App-Testing pull request #1
Opened 2023-06-21 08:48 UTC by rmiyoyo

# Work Done
-  [x] Added files from the To-Do List App repo

2023-06-22 21:03 UTC, Developer-Kingz requested changes
Nice job you have done so far, you are almost there. But there are somethings that can be improved upon. 
- it would be nice if your code is formatted properly as this will make it easily readable and understandable by anyone who goes through it.
- your HTML should be written using the right semantic tags for each part and sections.
- Also there are some repetitions in your code, it should be DRY to ensure it follows javascript best practice

2023-06-22 21:03 UTC, Developer-Kingz commented on modules/fillActivities.js
> +const fillActivities = (activities) => {
Nice job you have done so far, but it would be nice if you installed a code formatter extension such as prettier in your Vs code so that it can help format your code properly. you can also set it up to format code on save.

2023-06-22 21:03 UTC, Developer-Kingz commented on src/index.html
> +    <div class="activity-zone">
A section tag should be added before this div, as this will make it semantically correct

2023-06-23 07:36 UTC, rmiyoyo commented on modules/fillActivities.js
> +const fillActivities = (activities) => {
Thank you for this. I have installed the extension for use.

2023-06-23 08:16 UTC, Developer-Kingz commented
Nice work @rmiyoyo . There is nothing else to be done.

2023-06-23 08:16 UTC, closed without merging